config/routes.rb
RubyMedicalCenter::Application.routes.draw do
  devise_for :users

  resources :dashboard, :path => "admin/dashboard"

	namespace :admin do
    
		resources :users do
		  member do
		    get :enable
      end
    end
    
    resources :accounts do
      member do
        get :edit_user
      end
    end
		
		resources :patients do
		  member do
		    get :enable
      end
    end
    
    resources :servants do
      member do
        get :enable
      end
    end
    
    resources :doctors do
      member do
        get :enable
      end
    end
    
    resources :administratives do
      member do
        get :enable
      end
    end
    
    resources :nurses do
      member do
        get :enable
      end
    end
    
    resources :agendas
    
    resources :consultations do
      member do
        get :enable
      end
    end 
    
	end	
		
  get "home/action_forbidden"
	match 'home' => 'home#index'

   root :to => "home#index"

end

app/models/consultation.rb
class Consultation < ActiveRecord::Base
  belongs_to :specialty
  belongs_to :servant
  belongs_to :patient
  belongs_to :health_plan
end

app/controllers/admin/consultations_controller.rb
class Admin::ConsultationsController < ApplicationController
  layout 'admin/application'
	respond_to :html, :xml, :js, :json
	before_filter :admin?
	
  def index
    @consultations = Consultation.order 'consultation_date DESC'
    
    respond_with @consultations
  end
  
  def new
    @consultation = Consultation.new
    @specialties = Specialty.order 'name ASC'
    
    if params[:specialty_id].present?
      specialty = Specialty.find params[:specialty_id]
      @doctors = []
      specialty.doctor_specialties.each do |doctor|
        @doctors << doctor
      end
      
      @patients = select_patient    
    end
    #@doctors = Doctor.order 'name ASC'
    
    #@health_plans = @patients.health_plan.name
  end
  
  private
  
    def select_patient
      patients = Patient.all
      patients.each do |patient|
        if patient.user.id == current_user.id
          @patients = Patient.where "id = #{patient.id}"
        else
          @patients = Patient.order 'name ASC'
        end
      end
      @patients
    end
end

app/helpers/admin/consultations_helper.rb
module Admin::ConsultationsHelper
end

app/views/admin/consultations/_form.html.erb
<table>
  <tr>
    <td><%= f.label I18n.t :specialty %>:</td>
    <td>
      <%= f.collection_select(:specialty_id, @specialties, :id, :name, {:prompt => 'Selecione'} ) %>
    </td>
  </tr>
  <tr id="doctor">
  </tr>
  <tr id="patient">
  </tr>
  <tr id="health_plan">
  </tr>
  <tr id="date">
  </tr>
</table>

app/views/admin/consultations/index.html.erb
        <%= render :partial => 'admin/shared/subnav_agendas'%>
        
        <article class="article">
          <h2><%= I18n.t :consultation_register %></h2>
					<h4>>> <%= link_to I18n.t(:new_consultation), new_admin_consultation_path %></h4>
          <div class="line"></div> 
          
          <div class="articleBody clear">
            <table>
		        	<thead>
		        		<th><%= I18n.t :specialty %></th>
		        		<th><%= I18n.t :doctor %></th>
		        		<th><%= I18n.t :consultation_date %></th>
		        		<th><%= I18n.t :patient %></th>
		        		<th><%= I18n.t :health_plan %></th>
		        		<th><%= I18n.t :enabled %></th>
		        		<th></th>
		        		<th></th>
		        		<th></th>
		        	</thead>
		        	<% @consultations.each do |consultation| %>
		        	<tr>
		        		<td><%= consultation.specialty.name %></td>
		        		<td><%= consultation.servant.name %></td>
		        		<td><%= consultation.consultation_date.strftime("%d/%m/%Y") %>
		        		<td><%= consultation.patient.name %></td>
		        		<td><%= consultation.health_plan.name %></td>
		        		<td><%= link_to show_enabled_icon(consultation.enabled), enable_admin_consultation_path(consultation.id), :confirm => enable_confirm_message(consultation.enabled) %></td>
		        		<td><%= link_to I18n.t(:view), admin_consultation_path(consultation) %></td>
		        		<td><%= link_to I18n.t(:edit), edit_admin_consultation_path(consultation) %></td>
		        		<td><%= button_to I18n.t(:delete), {:action => "destroy", :id => consultation.id}, :method => :delete %></td>
		        	</tr>
		        	<% end %>
		        </table>
          </div>
        </article>

app/views/admin/consultations/new.html.erb
<script>
  $(document).ready(function(){
    //$('#consultation_patient_id').hide(6);
    $('#consultation_specialty_id').change(function(){
      var specialty = $(this).val();
      $.ajax({
        url: this.href,
        type: 'get',
        data: {specialty_id: specialty},
        dataType: 'script'
      });

    });
  });
</script>
        <%= render :partial => 'admin/shared/subnav_agendas'%>
        
        <article class="article">
        	<h2><%= I18n.t :new_consultation_register %></h2>

          <div class="line"></div>    

          <div class="articleBody clear">
          	<%= form_for(@consultation, :as => :consultation, :url => admin_consultations_path, :html => { :method => :post, :class => "form", :id => "form" }) do |f| %>
      				<%= render :partial => 'form', :locals => { :f => f }  %>
      				<%= submit_tag I18n.t(:create) %>
      				<%= link_to I18n.t(:cancel), admin_consultations_path %>
    				<% end %>
          </div>
        </article>  

app/views/admin/consultations/new.js.erb
$('#doctor').empty();
$('#doctor').append("<td><%= I18n.t :doctors %>:</td><td><select id='consultation_doctor_id' name='consultation[:doctor_id]'><option></option>");
<% @doctors.each do |doctor| %>
  $('#consultation_doctor_id').append("<option value='<%= doctor.servant.id %>'><%= doctor.servant.name %></option>");
<% end %>
$('#preview').append("</select></td>");

$('#patient').empty();
$('#patient').append("<td><%= I18n.t :patients %>:</td><td><select id='consultation_patient_id' name='consultation[:patient_id]'><option></option>");
<% @patients.each do |patient| %>
  $('#consultation_patient_id').append("<option value='<%= patient.id %>'><%= patient.name %></option>");
<% end %>
$('#preview').append("</select></td>");