config/routes.rb
RubyMedicalCenter::Application.routes.draw do
  devise_for :users

  resources :dashboard, :path => "admin/dashboard"

	namespace :admin do
    
		resources :users do
		  member do
		    get :enable
      end
    end
    
    resources :accounts do
      member do
        get :edit_user
      end
    end
		
		resources :patients do
		  member do
		    get :enable
      end
    end
    
    resources :servants do
      member do
        get :enable
      end
    end
    
    resources :doctors do
      member do
        get :enable
      end
    end
    
    resources :administratives do
      member do
        get :enable
      end
    end
    
    resources :nurses do
      member do
        get :enable
      end
    end
    
    resources :agendas
    
    resources :consultations do
      member do
        get :enable
      end
    end 
    
	end	
		
  get "home/action_forbidden"
	match 'home' => 'home#index'

   root :to => "home#index"

end

app/models/doctor.rb
class Doctor < Servant

  def save_doctor_specialties(specialties)
    specialties.each_pair do |key, value|
      if value == "1"
        DoctorSpecialty.create(
          :servant_id => self.id,
          :specialty_id => key
        )
      end
    end
  end
  
  def save_doctor_health_plans(health_plans)
    health_plans.each_pair do |key, value|
      if value == "1"
        DoctorHealthPlan.create(
          :servant_id => self.id,
          :health_plan_id => key
        )
      end
    end
  end  
  
  def save_users
    user = User.create(
      :name => self.name,
      :login => self.name.mb_chars.normalize(:kd).downcase.gsub(' ', '').gsub(/\W/,''),
      :email => self.email,
      :password => self.name.mb_chars.normalize(:kd).downcase.gsub(' ', '').gsub(/\W/,''),
      :password_confirmation => self.name.mb_chars.normalize(:kd).downcase.gsub(' ', '').gsub(/\W/,''),
      :enabled => 1,
      :can_login => 1
      )        
        
    role = Role.find 4
    user.roles << role
    user.servant_id = self.id
    user.save
  end

end

app/controllers/admin/doctors_controller.rb
class Admin::DoctorsController < ApplicationController
  layout 'admin/application'
	respond_to :html, :xml, :js
	before_filter :admin?
	
  def index
    @doctors = Doctor.order 'name ASC'
    
    respond_with @doctors
  end
  
  def new
    @doctor = Doctor.new
    @specialties = Specialty.order 'name ASC'
    @states = State.order 'name ASC'
    @health_plans = HealthPlan.where('id > 1 AND enabled = 1').order('name ASC')
    
    respond_with @doctor
  end
  
  def create
    @doctor = Doctor.new params[:doctor]
    
    respond_to do |format|
      if @doctor.save
        @doctor.save_doctor_specialties params[:specialty]
        @doctor.save_doctor_health_plans params[:health_plan]
        @doctor.save_users 
        
        format.html { redirect_to(admin_doctors_url, :notice => 'Doctor was successfully created.') }
        format.xml  { render :xml => @doctor, :status => :created, :location => @doctor }
      else
        format.html { render :action => :new }
        format.xml  { render :xml => @doctor.errors, :status => :unprocessable_entity }
      end
    end
    
  end
  
  def show
    @doctor = Doctor.find params[:id]
    
    respond_with @doctor
  end
  
  def edit
    @doctor = Doctor.find params[:id]
    @specialties = Specialty.order 'name ASC'
    @states = State.order 'name ASC'
    @health_plans = HealthPlan.where('id > 1 AND enabled = 1').order('name ASC')
    
    respond_with @doctor
  end

  def update
    @doctor = Doctor.find params[:id]
    
    specialty_clean = "DELETE FROM doctor_specialties WHERE servant_id = #{@doctor.id}"
    ActiveRecord::Base::connection().update(specialty_clean)

    @doctor.save_doctor_specialties params[:specialty]
        
    
    health_plan_clean = "DELETE FROM doctor_health_plans WHERE servant_id = #{@doctor.id}"
    ActiveRecord::Base::connection().update(health_plan_clean)

    @doctor.save_doctor_health_plans params[:health_plan]

    respond_to do |format|
      if @doctor.update_attributes params[:doctor]
        format.html { redirect_to(admin_doctors_url, :notice => 'Doctor was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => :edit }
        format.xml  { render :xml => @doctor.errors, :status => :unprocessable_entity }
      end
    end
    
  end

  def destroy
    @doctor = Doctor.find(params[:id]).destroy
		
    respond_to do |format|
      format.html { redirect_to admin_doctors_url }
      format.xml  { head :ok }
    end
  end
  
  def enable
    @doctor = Doctor.find params[:id]
    @doctor.enabled = (@doctor.enabled) ? false : true

    if @doctor.save
      flash[:success] = (@doctor.enabled) ? I18n.t(:doctor_enabled) : I18n.t(:doctor_disabled)
    else
      flash[:error] = I18n.t :doctor_enable_error
    end
    
    redirect_to admin_doctors_path
    
  end

  
end

app/helpers/admin/doctors_helper.rb
module Admin::DoctorsHelper
 
  def show_specialty(doctor)
    specialties_td = "<td>"
    doctor.specialties.each do |specialty|
      specialties_td << specialty.name
      specialties_td << "<br/>"
    end
    specialties_td << "</td>"
    raw specialties_td
  end
  
  def show_health_plan(doctor)
    health_plans_td = "<td>"
    doctor.health_plan.each do |health_plan|
      health_plans_td << health_plan.name
      health_plans_td << "<br/>"
    end
    health_plans_td << "</td>"
    raw health_plans_td
  end
  
end

app/views/admin/doctors/_form.html.erb
<table>
  <tr>
    <td><%= f.label I18n.t :name %>:</td>
    <td><%= f.text_field :name %></td> 
  </tr>
  <tr>
    <td><%= f.label I18n.t :birth %>:</td>
    <td>
    <%= f.date_select :birth, 
		          :use_month_numbers => true,
		          :order => [:day, :month, :year],
		          :default => Time.now,
		          :start_year => 1900,
		          :end_year => Time.now.year + 1 %></td>
  </tr>
  <tr>
    <td><%= f.label I18n.t :sex %>:</td>
    <td>
      <%= f.radio_button :sex, 'Masculino', :checked => true %> M
      <%= f.radio_button :sex, 'Feminino', :checked => false %> F 
    </td>
  </tr>
  <tr>
    <td><%= f.label I18n.t :cpf %>:</td>
    <td><%= f.text_field :cpf %></td>
  </tr>
  <tr>
    <td><%= f.label I18n.t :state %>:</td>
    <td>
      <%= f.collection_select(:state_id, @states, :id, :name, {:prompt => 'Selecione'} ) %>
    </td>
  </tr>
    <tr>
    <td><%= f.label I18n.t :address %>:</td>
    <td><%= f.text_field :address %></td>
  </tr>
  <tr>
    <td><%= f.label I18n.t :number %>:</td>
    <td><%= f.text_field :number %></td>
  </tr>
  <tr>
    <td><%= f.label I18n.t :complement %>:</td>
    <td><%= f.text_field :complement %></td>
  </tr>
  <tr>
    <td><%= f.label I18n.t :zip_code %>:</td>
    <td><%= f.text_field :zip_code %></td>
  </tr>
  <tr>
    <td><%= f.label I18n.t :district %>:</td>
    <td><%= f.text_field :district %></td>
  </tr>
  <tr>
    <td><%= f.label I18n.t :city %>:</td>
    <td><%= f.text_field :city %></td>
  </tr>
  <tr>
    <td><%= f.label I18n.t :telephone %>:</td>
    <td>
      <%= f.text_field :area_code, :size => 3 %><%= f.text_field :telephone %> 
    </td>
  </tr>
  <tr>
    <td><%= f.label I18n.t :mobile %>:</td>
    <td><%= f.text_field :mobile %></td>
  </tr>
  <tr>
    <td><%= f.label I18n.t :email %>:</td>
    <td><%= f.text_field :email %></td>
  </tr>
  <tr>
    <td><%= f.label I18n.t :enabled %>:</td>
    <td><%= f.check_box :enabled %></td>
  </tr>
  <tr>
    <td><%= f.label I18n.t :crm %>:</td>
    <td><%= f.text_field :crm %></td>
  </tr>
  <tr>
    <td><%= f.label I18n.t :specialty %>:</td>  
    <td>  
  <% @specialties.each do |specialty| %>
      <%= check_box :specialty, "#{specialty.id}" %><%= specialty.name %>
    <br/>
  <% end %>
    </td>
  <tr>
    <td><%= f.label I18n.t :health_plan %>:</td>  
    <td>
    <% @health_plans.each do |health_plan| %>    
      <%= check_box :health_plan, "#{health_plan.id}" %><%= health_plan.name %>    
      <br/>
    <% end %>
    </td>
  </tr>  
  
</table>

app/views/admin/doctors/index.html.erb
        <%= render :partial => 'admin/shared/subnav_servants'%>
        
        <article class="article">
          <h2><%= I18n.t :doctor_register %></h2>
					<h4>>> <%= link_to I18n.t(:new_doctor), new_admin_doctor_path %></h4>
					
          <div class="line"></div>    

          <div class="articleBody clear">  
		        <table>
		        	<thead>
		        		<th><%= I18n.t :name %></th>
		        		<th><%= I18n.t :email %></th>
		        		<th><%= I18n.t :telephone %></th>
		        		<th><%= I18n.t :city %></th>
		        		<th><%= I18n.t :state %></th>
		        		<th><%= I18n.t :enabled %></th>
		        		<th></th>
		        		<th></th>
		        		<th></th>
		        	</thead>
		        	<% @doctors.each do |doctor| %>
		        	<tr>
		        		<td><%= doctor.name %></td>
		        		<td><%= doctor.email %></td>
		        		<td><%= doctor.area_code %> - <%= doctor.telephone %></td>
		        		<td><%= doctor.city %></td>
		        		<td><%= doctor.state.name %></td>
		        		<td><%= link_to show_enabled_icon(doctor.enabled), enable_admin_doctor_path(doctor.id), :confirm => enable_confirm_message(doctor.enabled) %></td>
		        		<td><%= link_to I18n.t(:view), admin_doctor_path(doctor) %></td>
		        		<td><%= link_to I18n.t(:edit), edit_admin_doctor_path(doctor) %></td>
		        		<td><%= button_to I18n.t(:delete), {:action => "destroy", :id => doctor.id}, :method => :delete %></td>
		        	</tr>
		        	<% end %>
		        </table>
          </div>
        </article>

app/views/admin/doctors/new.html.erb
			<%= render :partial => 'admin/shared/subnav_servants'%>
			
				<article class="article">
        	<h2><%= I18n.t :new_doctor_register %></h2>

          <div class="line"></div>    

          <div class="articleBody clear">
          	<%= form_for(@doctor, :as => :doctor, :url => admin_doctors_path, :html => { :method => :post, :class => "form", :id => "form" }) do |f| %>
      				<%= render :partial => 'form', :locals => { :f => f }  %>
      				<%= submit_tag I18n.t(:create) %>
      				<%= link_to I18n.t(:cancel), admin_doctors_path %>
    				<% end %>
          </div>
        </article>       	
        	
        	

app/views/admin/doctors/show.html.erb
        <%= render :partial => 'admin/shared/subnav_servants'%>
        
        <article class="article">
        	<h2><%= I18n.t :info %></h2>

          <div class="line"></div>    

          <div class="articleBody clear">
            <table>
              <tr>
                <td><%= I18n.t :name %>:</td>
                <td><%= @doctor.name %></td> 
              </tr>
              <tr>
                <td><%= I18n.t :birth %>:</td>
                <td>
                <%= @doctor.birth.strftime("%d-%m-%Y") %></td>
              </tr>
              <tr>
                <td><%= I18n.t :sex %>:</td>
                <td>
                  <%= @doctor.sex %> 
                </td>
              </tr>
              <tr>
                <td><%= I18n.t :cpf %>:</td>
                <td><%= @doctor.cpf %></td>
              </tr>
              <tr>
                <td><%= I18n.t :state %>:</td>
                <td>
                  <%= @doctor.state.name %>
                </td>
              </tr>
                <tr>
                <td><%= I18n.t :address %>:</td>
                <td><%= @doctor.address %></td>
              </tr>
              <tr>
                <td><%= I18n.t :number %>:</td>
                <td><%= @doctor.number %></td>
              </tr>
              <tr>
                <td><%= I18n.t :complement %>:</td>
                <td><%= @doctor.complement %></td>
              </tr>
              <tr>
                <td><%= I18n.t :zip_code %>:</td>
                <td><%= @doctor.zip_code %></td>
              </tr>
              <tr>
                <td><%= I18n.t :district %>:</td>
                <td><%= @doctor.district %></td>
              </tr>
              <tr>
                <td><%= I18n.t :city %>:</td>
                <td><%= @doctor.city %></td>
              </tr>
              <tr>
                <td><%= I18n.t :telephone %>:</td>
                <td>
                  <%= @doctor.area_code %><%= @doctor.telephone %> 
                </td>
              </tr>
              <tr>
                <td><%= I18n.t :mobile %>:</td>
                <td><%= @doctor.mobile %></td>
              </tr>
              <tr>
                <td><%= I18n.t :email %>:</td>
                <td><%= @doctor.email %></td>
              </tr>
              <tr>
                <td><%= I18n.t :enabled %>:</td>
                <td><%= @doctor.enabled %></td>
              </tr>
              <tr>
                <td><%= I18n.t :crm %>:</td>
                <td><%= @doctor.crm %></td>
              </tr>
              <tr>
                <td><%= I18n.t :specialty %>:</td>
                <%= show_specialty(@doctor)%>
              </tr>
              <tr>
                <td><%= I18n.t :health_plan %>:</td>
                <%= show_health_plan(@doctor)%>
              </tr>
            </table>
          </div>
        </article> 