config/routes.rb
RubyMedicalCenter::Application.routes.draw do
  devise_for :users

  resources :dashboard, :path => "admin/dashboard"

	namespace :admin do
    
		resources :users do
		  member do
		    get :enable
      end
    end
    
    resources :accounts do
      member do
        get :edit_user
      end
    end
		
		resources :patients do
		  member do
		    get :enable
      end
    end
    
    resources :servants do
      member do
        get :enable
      end
    end
    
    resources :doctors do
      member do
        get :enable
      end
    end
    
    resources :administratives do
      member do
        get :enable
      end
    end
    
    resources :nurses do
      member do
        get :enable
      end
    end
    
    resources :agendas
    
    resources :consultations do
      member do
        get :enable
      end
    end 
    
	end	
		
  get "home/action_forbidden"
	match 'home' => 'home#index'

   root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base

  has_and_belongs_to_many :roles
  has_one :servant
  has_one :patient

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :login, :enabled, :can_login, :email, :password, :password_confirmation, :servant_id, :patient_id
  
  validates_presence_of :name, :login
  
  def save_role(role)
    role.each_value do |r|      
      rl = Role.find r
      self.roles << rl
    end
  end
  
  def self.can_login
    '/users/sign_in'
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	layout 'admin/application'
	respond_to :html, :xml, :js
	before_filter :admin?
	
	def index
		@users = User.order 'name ASC'
		
		respond_with @users
	end
	
	def new
		@user = User.new
		@roles = Role.where(:enabled => 1).order('name ASC')
		
		respond_with @users
	end
	
	def create
		@user = User.new params[:user]
		@user.save_role params[:role]
		
		respond_to do |format|
			if @user.save
				format.html { redirect_to(admin_users_url, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
			else
				format.html { render :action => :new }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
			end
		end
	end
	
	def show
		@user = User.find params[:id]
		
		respond_with @user
	end
	
	def edit
		@user = User.find params[:id]
		@roles = Role.where(:enabled => 1).order('name ASC')
		@selected = @user.roles[0].id unless @selected = @user.roles[0].nil?
	end
	
	def update
		@user = User.find params[:id]
		
		role_clean = "DELETE FROM roles_users WHERE user_id = #{@user.id}"
    ActiveRecord::Base::connection().update(role_clean)
    
    @user.save_role params[:role]
    
		respond_to do |format|
      if @user.update_attributes params[:user]
        format.html { redirect_to(admin_users_url, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => :edit }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
    
	end
	
	def destroy
		User.find(params[:id]).destroy
		
		respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.xml  { head :ok }
    end
	end
	
	def enable
    @user = User.find params[:id]
    @user.enabled = (@user.enabled) ? false : true

    if @user.save
      flash[:success] = (@user.enabled) ? I18n.t(:user_enabled) : I18n.t(:user_disabled)
    else
      flash[:error] = I18n.t :user_enable_error
    end
    
    redirect_to admin_users_path
    
  end
	
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<table>
  <tr>
    <td class="last"><%= f.label I18n.t :name %></td>
    <td class="middle"><%= f.text_field :name %></td>
  </tr>
  <tr>
    <td class="last"><%= f.label I18n.t :email %></td>
    <td class="middle"><%= f.text_field :email %></td>
  </tr>
  <tr>
    <td class="last"><%= f.label I18n.t :login %></td>
    <td class="middle"><%= f.text_field :login %></td>
  </tr>
  <tr>
    <td class="last"><%= f.label :password, f.object.new_record? ? nil : "Change password" %></td>
    <td class="middle"><%= f.password_field :password %></td>
  </tr>
  <tr>
    <td class="last"><%= f.label I18n.t :password_confirmation %></td>
    <td class="middle"><%= f.password_field :password_confirmation %></td>
  </tr>
  <tr>
    <td class="last"><%= f.label I18n.t :can_login %></td>
    <td class="middle"><%= f.check_box :can_login %></td>
  </tr>
  <tr>
    <td class="last"><%= f.label I18n.t :enabled %></td>
    <td class="middle"><%= f.check_box :enabled %></td>
  </tr>
  <tr>
    <td class="last"><%= f.label I18n.t :roles %></td>
    <td class="middle"><%= collection_select(:role, '1', @roles, :id, :name, {:selected => @selected} ) %></td>
  </tr>
</table>

app/views/admin/users/edit.html.erb
			<%#= render :partial => 'admin/shared/subnav' %>
			
				<article class="article">
         	<h2><%= I18n.t :edit_user_register %>s</h2>

          <div class="line"></div>    

          <div class="articleBody clear"> 
          	<%= form_for(@user, :as => :user, :url => admin_user_path, :html => {:method => :put, :id => "form", :class => "form"}) do |f|%>
          		<%= render :partial => 'form', :locals => {:f => f} %>
          		<%= submit_tag I18n.t :update %>
        			<%= link_to I18n.t(:cancel), admin_users_path%>
		        <% end %>
          </div>
        </article>

app/views/admin/users/index.html.erb
			<%#= render :partial => 'admin/shared/subnav' %>
			
				<article class="article">
         	<h2><%= I18n.t :user_register %></h2>
					<h4>>> <%= link_to I18n.t(:new_user), new_admin_user_path %></h4>
					
          <div class="line"></div>    

          <div class="articleBody clear">  
		        <table>
		        	<thead>
		        		<th><%= I18n.t :name %></th>
		        		<th><%= I18n.t :login %></th>
		        		<th><%= I18n.t :email %></th>
		        		<th><%= I18n.t :enabled %></th>
		        		<!--<th><%#= I18n.t :can_login %></th>-->
		        		<th></th>
		        		<th></th>
		        		<th></th>
		        	</thead>
		        	<% @users.each do |user| %>
		        	<tr>
		        		<td><%= user.name %></td>
		        		<td><%= user.login %></td>
		        		<td><%= user.email%></td>
		        		<td><%= link_to show_enabled_icon(user.enabled), enable_admin_user_path(user.id), :confirm => enable_confirm_message(user.enabled) %></td>
		        		<!--<td><%#= user.can_login%></td>-->
		        		<td><%= link_to I18n.t(:view), admin_user_path(user) %></td>
		        		<td><%= link_to I18n.t(:edit), edit_admin_user_path(user) %></td>
		        		<td><%= button_to I18n.t(:delete), {:action => "destroy", :id => user.id}, :method => :delete %></td>
		        	</tr>
		        	<% end %>
		        </table>
          </div>
        </article>
        

app/views/admin/users/new.html.erb
			<%#= render :partial => 'admin/shared/subnav' %>
			
				<article class="article">
         	<h2><%= I18n.t :new_user_register %></h2>

          <div class="line"></div>    

          <div class="articleBody clear"> 
          	<%= form_for(@user, :as => :user, :url => admin_users_path, :html => {:id => "form", :class => "form"}) do |f|%>
          		<%= render :partial => 'form', :locals => {:f => f} %>
          		<%= submit_tag I18n.t :create %>
        			<%= link_to I18n.t(:cancel), admin_users_path%>
		        <% end %>
          </div>
        </article>

app/views/admin/users/show.html.erb
				<article class="article">
         	<h2><%= I18n.t :show_user_register %></h2>

          <div class="line"></div>    

          <div class="articleBody clear"> 
          	<table>
							<tr>
								<td class="last"><%= I18n.t :name %></td>
								<td class="middle"><%= @user.name %></td>
							</tr>
							<tr>
								<td class="last"><%= I18n.t :email %></td>
								<td class="middle"><%= @user.email %></td>
							</tr>
						</table>
          </div>
        </article>