config/routes.rb
RubyMedicalCenter::Application.routes.draw do
  devise_for :users

  resources :dashboard, :path => "admin/dashboard"

	namespace :admin do
    
		resources :users do
		  member do
		    get :enable
      end
    end
    
    resources :accounts do
      member do
        get :edit_user
      end
    end
		
		resources :patients do
		  member do
		    get :enable
      end
    end
    
    resources :servants do
      member do
        get :enable
      end
    end
    
    resources :doctors do
      member do
        get :enable
      end
    end
    
    resources :administratives do
      member do
        get :enable
      end
    end
    
    resources :nurses do
      member do
        get :enable
      end
    end
    
    resources :agendas
    
    resources :consultations do
      member do
        get :enable
      end
    end 
    
	end	
		
  get "home/action_forbidden"
	match 'home' => 'home#index'

   root :to => "home#index"

end

app/models/administrative.rb
class Administrative < Servant
  def save_users
    user = User.create(
      :name => self.name,
      :login => self.name.mb_chars.normalize(:kd).downcase.gsub(' ', '').gsub(/\W/,''),
      :email => self.email,
      :password => self.name.mb_chars.normalize(:kd).downcase.gsub(' ', '').gsub(/\W/,''),
      :password_confirmation => self.name.mb_chars.normalize(:kd).downcase.gsub(' ', '').gsub(/\W/,''),
      :enabled => 1,
      :can_login => 1
      )        
        
    role = Role.find 3
    user.roles << role
    user.servant_id = self.id
    user.save
  end
end

app/models/consultation.rb
class Consultation < ActiveRecord::Base
  belongs_to :specialty
  belongs_to :servant
  belongs_to :patient
  belongs_to :health_plan
end

app/models/doctor.rb
class Doctor < Servant

  def save_doctor_specialties(specialties)
    specialties.each_pair do |key, value|
      if value == "1"
        DoctorSpecialty.create(
          :servant_id => self.id,
          :specialty_id => key
        )
      end
    end
  end
  
  def save_doctor_health_plans(health_plans)
    health_plans.each_pair do |key, value|
      if value == "1"
        DoctorHealthPlan.create(
          :servant_id => self.id,
          :health_plan_id => key
        )
      end
    end
  end  
  
  def save_users
    user = User.create(
      :name => self.name,
      :login => self.name.mb_chars.normalize(:kd).downcase.gsub(' ', '').gsub(/\W/,''),
      :email => self.email,
      :password => self.name.mb_chars.normalize(:kd).downcase.gsub(' ', '').gsub(/\W/,''),
      :password_confirmation => self.name.mb_chars.normalize(:kd).downcase.gsub(' ', '').gsub(/\W/,''),
      :enabled => 1,
      :can_login => 1
      )        
        
    role = Role.find 4
    user.roles << role
    user.servant_id = self.id
    user.save
  end

end

app/models/doctor_health_plan.rb
class DoctorHealthPlan < ActiveRecord::Base
  belongs_to :servant
  belongs_to :health_plan
end

app/models/doctor_specialty.rb
class DoctorSpecialty < ActiveRecord::Base
  belongs_to :servant
  belongs_to :specialty
end

app/models/health_plan.rb
class HealthPlan < ActiveRecord::Base
  has_many :doctor_health_plans
  has_many :servants, :through => :doctor_health_plans
  has_many :patients
  has_many :consultations
end

app/models/nurse.rb
class Nurse < Servant
  has_and_belongs_to_many :specifications
  
  def save_specifications(specifications)
    specifications.each_value do |id|
      specification = Specification.find id
      self.specifications << specification
    end
  end
end

app/models/patient.rb
class Patient < ActiveRecord::Base

	belongs_to :state
	has_one :user
	belongs_to :health_plan
	belongs_to :room
	has_many :consultations
	
	validates_presence_of :name, :message => 'Deve ser preenchido' 
	validates_presence_of :address, :message => 'Deve ser preenchido' 
	validates_presence_of :number, :message => 'Deve ser preenchido'
	validates_presence_of :district, :message => 'Deve ser preenchido' 
	validates_presence_of :city, :message => 'Deve ser preenchido'
	validates_presence_of :email
	validates_presence_of :cpf
	validates_presence_of :zip_code
	validates_presence_of :state_id
	validates_presence_of :room_id
	validates_presence_of :health_plan_id
	validates_length_of :cpf, :is => 11, :message => 'Deve ter 11 numeros'
	validates_length_of :zip_code, :is => 8, :message => 'Deve ter 8 numeros'
	validates_length_of :area_code, :is => 2, :allow_blank => true
  validates_length_of :telephone, :is => 8, :allow_blank => true
  validates_length_of :mobile, :is => 8, :allow_blank => true
  
  def save_users
    user = User.create(
      :name => self.name,
      :login => self.name.mb_chars.normalize(:kd).downcase.gsub(' ', '').gsub(/\W/,''),
      :email => self.email,
      :password => self.name.mb_chars.normalize(:kd).downcase.gsub(' ', '').gsub(/\W/,''),
      :password_confirmation => self.name.mb_chars.normalize(:kd).downcase.gsub(' ', '').gsub(/\W/,''),
      :enabled => 1,
      :can_login => 1
      )        
        
    role = Role.find 6
    user.roles << role
    user.patient_id = self.id
    user.save
  end

end

app/models/permission.rb
class Permission < ActiveRecord::Base
  has_and_belongs_to_many :role
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :permissions
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :patients
end

app/models/servant.rb
class Servant < ActiveRecord::Base

	belongs_to :state
	has_many :doctor_specialties
  has_many :specialties, :through => :doctor_specialties
  has_many :doctor_health_plans
  has_many :health_plan, :through => :doctor_health_plans
  has_many :consultations
  has_one :user
  
	validates_presence_of :name, :message => 'Deve ser preenchido' 
	validates_length_of :cpf, :is => 11, :message => 'Deve ter 11 numeros'
	validates_presence_of :address, :message => 'Deve ser preenchido' 
	validates_presence_of :number, :message => 'Deve ser preenchido'
	validates_length_of :zip_code, :is => 8, :message => 'Deve ter 8 numeros'
	validates_presence_of :district, :message => 'Deve ser preenchido' 
	validates_presence_of :city, :message => 'Deve ser preenchido'
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
  has_many :doctor_specialties
  has_many :servants, :through => :doctor_specialties
  has_many :consultations
end

app/models/specification.rb
class Specification < ActiveRecord::Base
  has_and_belongs_to_many :nurses
end

app/models/state.rb
class State < ActiveRecord::Base

	has_many :patients
	has_many :servants

end

app/models/user.rb
class User < ActiveRecord::Base

  has_and_belongs_to_many :roles
  has_one :servant
  has_one :patient

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :login, :enabled, :can_login, :email, :password, :password_confirmation, :servant_id, :patient_id
  
  validates_presence_of :name, :login
  
  def save_role(role)
    role.each_value do |r|      
      rl = Role.find r
      self.roles << rl
    end
  end
  
  def self.can_login
    '/users/sign_in'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
	
	def action_forbidden
	  
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/shared/_nav_header.html.erb
				<nav class="clear">
        	<ul>
        	  <% if has_access?('dashboard/index') %>
        	  <li><%= link_to I18n.t(:dashboard), dashboard_index_path %></li>
        	  <% end %>
        	  <% if has_access?('admin/agendas/index') %>
            <li><%= link_to I18n.t(:agendas), admin_agendas_path %></li>
            <% end %>
            <li><a href="#">Financeiro</a></li>
            <% if has_access?('admin/servants/index') %>
            <li><%= link_to I18n.t(:servants), admin_servants_path %></li>
            <% end %>
            <% if has_access?('admin/patients/index') %>
            <li><%= link_to I18n.t(:patients), admin_patients_path %></li>
            <% end %>
            <% if has_access?('admin/users/index') %>
            <li><%= link_to I18n.t(:users), admin_users_path %></li>
            <% end %>
            <li><a href="#">Histórico</a></li>
            <li><a href="#">Sobre</a></li>
          </ul>
        </nav>


app/views/admin/shared/_nav_sidebar.html.erb
				<aside class="sidebar">
        	<h3>Menu Usuário</h3>
        	
        	<div class="line"></div>
        	
					<vertical class="menu">
        		<ul>
		      	  <li><a href="#">Contas a Pagar</a></li>
		          <li><a href="#">Contas a receber</a></li>
		          <li><a href="#">Consultas</a></li>
		          <li><a href="#">Funcionários</a></li>
		          <li><a href="#">Pacientes</a></li>
		          <li><a href="#">Usuários</a></li>
          	</ul>
        	</vertical>
        </aside>

app/views/admin/shared/_subnav.html.erb
<!--				<subnav class="clear">
        	<ul>
        	  <li><a href="#">Contas a Pagar</a></li>
            <li><a href="#">Contas a Receber</a></li>
            <li><a href="#">Funcionários</a></li>
            <li><%#= link_to I18n.t(:patients), :controller => :patients %></li>
            <li><%#= link_to I18n.t(:users), :controller => :users %></li>
          </ul>
        </subnav>-->

app/views/admin/shared/_subnav_agendas.html.erb
        <subnav class="clear">
        	<ul>
        	  <% if has_access?('admin/consultations/index')%>
        	  <li><%= link_to I18n.t(:consultations), admin_consultations_path %></li>
        	  <% end %>
          </ul>
        </subnav>

app/views/admin/shared/_subnav_servants.html.erb
        <subnav class="clear">
        	<ul>
        	  <% if has_access?('admin/doctors/index')%>
        	  <li><%= link_to I18n.t(:doctors), admin_doctors_path %></li>
        	  <% end %>
        	  <% if has_access?('admin/nurses/index') %>
            <li><%= link_to I18n.t(:nurse), admin_nurses_path %></li>
            <% end %>
            <% if has_access?('admin/administratives/index') %>
            <li><%= link_to I18n.t(:administrative), admin_administratives_path %></li>
            <% end %>
          </ul>
        </subnav>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html> <!-- The new doctype -->
<html>
	<head>
  	<meta charset="utf-8" />
  	<title>Medical Center</title>
  	<link rel="stylesheet" type="text/css" href="/stylesheets/admin/styles.css" /> 
  	<link rel="shortcut icon" href="/images/icons/batimento.ico" type="/images/icons/x-icon"/>
  	<%= javascript_include_tag 'jquery-1.4.2.min.js', 'jquery-ui-1.8.2.custom.min.js', 'rails.js', 'autocomplete-rails.js' %>
    <%= stylesheet_link_tag 'jquery-ui-1.8.2.custom.css' %>
    <%= csrf_meta_tag %>   
	</head>
	<body>    	
  	<section class="page">
  		<info>
  			<% if user_signed_in? %>
          <h5><%= link_to current_user.email, edit_admin_account_path(current_user.id) %> - <%= link_to "sair", destroy_user_session_path %></h5>
        <% end %>
  		</info>
  	
  		<div class="line"></div>
  	  
	    <header>            
        <hgroup>
        	<h1>Medical Center</h1>
        </hgroup>
        
        <%= render :partial => 'admin/shared/nav_header' %>
        
      </header>
            
      <section class="articles">
      
	      <div class="line"></div>               
	      
	      <p id="notice"><%= notice %></p>

       	<%= yield %>
      </section>

	        <footer>
          
          	<div class="line"></div>
           
           	<p>Medical Center &copy 2010.2 - Versão 3.0</p>
           
           	<a href="#" class="up">Go UP</a>
        	</footer>            
		</section>     
	</body>
</html>